<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.janboerman.cauldrondispensers</groupId>
    <artifactId>CauldronDispensers</artifactId>
    <version>1.9-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>CraftBukkitCompat</module>
        <module>BukkitPlugin</module>
        <module>PaperCompat</module>
        <module>Compat</module>
    </modules>

    <properties>
        <minecraft.version>26.3</minecraft.version>
    </properties>

    <scm>
        <developerConnection>scm:git:ssh://git@github.com/Jannyboy11/CauldronDispensers.git</developerConnection>
        <tag>v1.3</tag>
    </scm>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.16.0</version>
                <configuration>
                    <release>25</release>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <tagNameFormat>v${project.version}</tagNameFormat>
                    <preprationGoals>clean verify</preprationGoals>
                    <scmCommentPrefix>Maven Release Plugin:</scmCommentPrefix>
                    <scmReleaseCommitComment>@{prefix} Release @{releaseLabel}&#x1f389;!</scmReleaseCommitComment>
                    <scmDevelopmentCommitComment>@{prefix} Bump version. [skip ci]</scmDevelopmentCommitComment>
                    <scmRollbackCommitComment>@{prefix} Roll back.</scmRollbackCommitComment>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>