name: CauldronDispensers
author: Jannyboy11
main: com.janboerman.cauldrondispensers.CauldronDispensers
version: ${project.version}
api-version: 26.3
description: Makes dispensers with buckets interact with cauldrons.

folia-supported: true
