<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.janboerman.cauldrondispensers</groupId>
        <artifactId>CauldronDispensers</artifactId>
        <version>1.9</version>
    </parent>

    <artifactId>PaperCompat</artifactId>

    <pluginRepositories>
        <pluginRepository>
            <id>bytecode.space</id>
            <url>https://repo.bytecode.space/repository/maven-public/</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>ca.bkaw</groupId>
                <artifactId>paper-nms-maven-plugin</artifactId>
                <version>1.5</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.janboerman.cauldrondispensers</groupId>
            <artifactId>Compat</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>ca.bkaw</groupId>
            <artifactId>paper-nms</artifactId>
            <version>${minecraft.version}.build.31-alpha</version> <!-- See https://repo.papermc.io/repository/maven-public/io/papermc/paper/dev-bundle/ -->
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>