name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: 'microsoft'
          java-version: 25
          cache: 'maven'
      - name: Install CraftBukkit and Paper
        run: |
          wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 26.3 --compile craftbukkit
          mvn ca.bkaw:paper-nms-maven-plugin:init --pl :PaperCompat
      - name: Compile CauldronDispensers
        run: |
          mvn clean package install --batch-mode --update-snapshots -DfinalName=CauldronDispensers
      - name: Create tagged release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            BukkitPlugin/target/CauldronDispensers.jar
